// lang_data.js — Bilingual English/Urdu translation mappings.
// Attached to window.AGRINEXUS_TRANSLATIONS for universal access across static scripts.

window.AGRINEXUS_TRANSLATIONS = {
  en: {
    // Nav & Brand
    brand: "AgriNexus.Ai",
    nav_home: "Home",
    nav_about: "About",
    nav_features: "Features",
    nav_login: "Login",
    nav_dashboard: "Dashboard Login",
    
    // Hero Section
    hero_badge: "AI Agriculture Advisor",
    hero_title: "Transforming Agriculture for a Sustainable World",
    hero_subtitle: "AgriNexus empowers your farm to meet yield goals with precision. Track, verify, and protect every acre, ensuring optimal crop health and safeguarding the environment through innovative, data-driven AI solutions.",
    
    // About Section
    about_title: "Cultivating the Future with Agentic AI",
    about_desc: "AgriNexus isn't just a data dashboard—it's an autonomous agricultural advisor. By combining cutting-edge retrieval-augmented generation (RAG) with localized farm data, we provide farmers with actionable intelligence to maximize yield while minimizing environmental impact.",
    about_li1: "Analyzes multi-format soil reports instantly.",
    about_li2: "Provides highly confident pest control recommendations.",
    about_li3: "Ensures supply chain transparency for deforestation-free compliance.",
    
    // Features Section
    features_title: "Platform Features",
    features_desc: "Everything you need to optimize your fields, centralized in one intelligent platform.",
    feature_ocr_title: "OCR Disease Detection",
    feature_ocr_desc: "Upload images of affected crops and let our AI diagnose blight, rust, and pests with cited confidence scores.",
    feature_ingest_title: "Data Ingestion",
    feature_ingest_desc: "Seamlessly drag-and-drop PDFs, CSVs, and Word docs containing soil tests and yield data for instant parsing.",
    feature_forecast_title: "Yield Forecasting",
    feature_forecast_desc: "Interactive predictive modeling based on historical data, weather patterns, and current soil moisture levels.",
    
    // Footer
    footer_copy: "© 2026 AgriNexus. All rights reserved.",
    
    // Sidebar Navigation (Dashboard)
    side_dashboard: "Dashboard",
    side_chat: "AI Advisory",
    side_agronomy: "Smart Agronomy",
    side_plant_health: "Plant Diagnostics",
    side_role: "Farmer Account",
    side_logout: "Sign Out",
    
    // Dashboard Welcomes
    dash_welcome: "Welcome back",
    dash_fetching_date: "Fetching date...",
    dash_weather_title: "Live Local Weather",
    dash_weather_subtitle: "Current conditions at your registered location",
    dash_weather_loading: "Loading Weather...",
    dash_weather_location: "Loading location...",
    
    // Jump To
    jump_title: "Jump To:",
    jump_chat_title: "AI Advisory",
    jump_chat_desc: "Ask AgriNexus AI about weather updates, soil quality, or crop tips.",
    jump_agronomy_title: "Smart Agronomy",
    jump_agronomy_desc: "Plan crop layout and fertilizer schedules based on agricultural zone.",
    jump_plant_title: "Plant Diagnostics",
    jump_plant_desc: "Upload photos of your crop or plants to identify diseases and get fixes.",
    
    // AI Advisory Input
    chat_placeholder: "Ask about crops, diseases, or soil...",
    chat_welcome: "Hello! I am your AgriNexus AI Advisor. I can analyze soil reports, diagnose plant diseases from images, and recommend precision fertilizer schedules. How can I assist you today?",
    chat_history_title: "Query History",
    chat_history_loading: "Loading query history...",
    chat_attach_tooltip: "Attach file to chat",
    chat_history_tooltip: "View Query History",
    
    // Smart Agronomy View
    agro_zone_label: "Select Agricultural Zone",
    agro_advisory_title: "AI Health Assessment",
    agro_recommended_crops: "Recommended Crops",
    agro_crops_subtitle: "Top crops suited for your analyzed soil texture and current local parameters",
    agro_fit_confidence: "Type Fit Confidence",
    agro_diagnostic_metrics: "Diagnostic Metrics",
    agro_sand_silt: "Sand / Silt Fraction:",
    agro_temp: "Soil Temperature:",
    agro_moisture: "Soil Moisture (Hourly):",
    agro_humidity: "Relative Humidity:",
    agro_no_recs: "No recommendations generated.",
    agro_soil_type: "Soil Type",
    agro_moisture_state: "Moisture State",
    agro_ph_level: "pH Level",
    agro_organic_carbon: "Organic Carbon",
    agro_clay_content: "Clay Content",
    agro_bulk_density: "Bulk Density",
    agro_match_likelihood: "Match Likelihood",
    agro_accuracy: "Accuracy",
    agro_training_size: "Training size",
    agro_samples: "samples",
    agro_ready_title: "Ready for Analysis",
    agro_ready_desc: "Upload a soil image in the left panel to trigger TensorFlow.js diagnostics and physical property assessments.",
    agro_loading_weather: "Fetching live weather...",
    agro_weather_unavailable: "Weather data currently unavailable for",
    auth_login: "Login",
    auth_register: "Register",
    auth_email: "Email Address",
    auth_password: "Password",
    auth_select_role: "Select Role",
    auth_role_farmer: "Farmer",
    auth_role_admin: "Admin",
    auth_btn_access: "Access Dashboard",
    auth_full_name: "Full Name",
    auth_location: "City / Location",
    auth_land_size: "Land Size (Acres)",
    auth_btn_create: "Create Account",
    auth_select_land: "Select land size...",
    auth_land_less_1: "Less than 1 Acre",
    auth_land_1_5: "1 - 5 Acres",
    auth_land_5_10: "5 - 10 Acres",
    auth_land_10_20: "10 - 20 Acres",
    auth_land_20_50: "20 - 50 Acres",
    auth_land_50_plus: "50+ Acres",
    plant_card_title: "Plant Upload & Diagnosis",
    plant_drop_title: "Drop plant photo here",
    plant_drop_subtitle: "Supports JPG, JPEG, PNG up to 5MB",
    plant_btn_run: "Run Diagnosis",
    plant_btn_reset: "Reset Form",
    plant_history_title: "Previous Diagnostic Reports",
    plant_history_refresh: "Refresh Log",
    plant_th_img: "Plant Image",
    plant_th_species: "Identified Species",
    plant_th_confidence: "Confidence",
    plant_th_condition: "Health Condition",
    plant_th_issues: "Issues Found",
    plant_th_date: "Analysis Date",
    plant_th_action: "Action",
    plant_history_empty: "No diagnostic history available.",
    agro_live_weather: "Live Weather",
    agro_district_stats: "District Production stats (2022-23)",
    agro_soil_photo_title: "Soil Photo Diagnostics",
    agro_soil_drop_title: "Drop soil photo here",
    agro_soil_drop_subtitle: "or click to browse files",
    agro_btn_analyze: "Analyze Soil Health",
    plant_report_title: "Health Diagnostic Report",
    plant_empty_title: "No Analysis Executed",
    plant_empty_desc: "Upload a photo on the left to identify plant species and analyze crop health.",
    plant_lbl_species: "Species Identified",
    plant_lbl_health: "Health Score",
    plant_lbl_issues: "Detected Issues / Deficiencies",
    plant_lbl_insights: "AI Pathology Insights",
    plant_lbl_causes: "Likely Causes:",
    plant_lbl_treatment: "Actionable Treatment Guidance",
    plant_lbl_prevention: "Prevention Tips",
    plant_lbl_severity: "Severity Level"
  },
  ur: {
    // Nav & Brand
    brand: "ایگری نیکسس",
    nav_home: "ہوم",
    nav_about: "ہمارے بارے میں",
    nav_features: "خصوصیات",
    nav_login: "لاگ ان",
    nav_dashboard: "ڈیش بورڈ لاگ ان",
    
    // Hero Section
    hero_badge: "اے آئی زرعی مشیر",
    hero_title: "پائیدار دنیا کے لیے زراعت کی ترقی",
    hero_subtitle: "ایگری نیکسس آپ کے فارم کو درستگی کے ساتھ پیداواری اہداف حاصل کرنے کی صلاحیت فراہم کرتا ہے۔ جدید، ڈیٹا پر مبنی اے آئی سلوشنز کے ذریعے ہر ایکڑ کی حفاظت اور فصل کی بہترین صحت کو یقینی بنائیں۔",
    
    // About Section
    about_title: "اے آئی کے ساتھ مستقبل کی کاشتکاری",
    about_desc: "ایگری نیکسس صرف ایک ڈیٹا ڈیش بورڈ نہیں ہے—یہ ایک خود مختار زرعی مشیر ہے۔ جدید ترین ٹیکنالوجی اور مقامی فارم ڈیٹا کو ملا کر، ہم کسانوں کو پیداوار بڑھانے کے لیے بہترین رہنمائی فراہم کرتے ہیں۔",
    about_li1: "مٹی کی رپورٹس کا فوری تجزیہ کرتا ہے۔",
    about_li2: "پیسٹ کنٹرول کے لیے انتہائی معتبر سفارشات فراہم کرتا ہے۔",
    about_li3: "سپلائی چین میں شفافیت اور جنگلات کی کٹائی سے پاک تعمیل کو یقینی بناتا ہے۔",
    
    // Features Section
    features_title: "پلیٹ فارم کی خصوصیات",
    features_desc: "آپ کے کھیتوں کو بہتر بنانے کے لیے تمام ضروری خصوصیات ایک ہی ذہین پلیٹ فارم پر دستیاب ہیں۔",
    feature_ocr_title: "بیماریوں کی تشخیص",
    feature_ocr_desc: "متاثرہ فصلوں کی تصاویر اپ لوڈ کریں اور اے آئی کے ذریعے پیلی، کنگی اور کیڑوں کی تشخیص معتبر اسکورز کے ساتھ حاصل کریں۔",
    feature_ingest_title: "ڈیٹا اپ لوڈ",
    feature_ingest_desc: "مٹی کے ٹیسٹ اور پیداوار کے ڈیٹا پر مشتمل پی ڈی ایف، سی ایس وی اور ورڈ فائلز کو ڈریگ اینڈ ڈراپ کر کے فوری نتائج حاصل کریں۔",
    feature_forecast_title: "پیداوار کی پیشن گوئی",
    feature_forecast_desc: "تاریخی ڈیٹا، موسم کے حالات، اور مٹی کی نمی کی بنیاد پر پیداوار کا پیشن گوئی ماڈل۔",
    
    // Footer
    footer_copy: "© 2026 ایگری نیکسس۔ جملہ حقوق محفوظ ہیں۔",
    
    // Sidebar Navigation (Dashboard)
    side_dashboard: "ڈیش بورڈ",
    side_chat: "اے آئی ایڈوائزری",
    side_agronomy: "اسمارٹ ایگرونومی",
    side_plant_health: "پودوں کی تشخیص",
    side_role: "کسان اکاؤنٹ",
    side_logout: "لاگ آؤٹ",
    
    // Dashboard Welcomes
    dash_welcome: "خوش آمدید",
    dash_fetching_date: "تاریخ لوڈ ہو رہی ہے...",
    dash_weather_title: "مقامی موسم کا حال",
    dash_weather_subtitle: "آپ کے رجسٹرڈ مقام پر موجودہ حالات",
    dash_weather_loading: "موسم لوڈ ہو رہا ہے...",
    dash_weather_location: "مقام لوڈ ہو رہا ہے...",
    
    // Jump To
    jump_title: "فوری رسائی:",
    jump_chat_title: "اے آئی ایڈوائزری",
    jump_chat_desc: "ایگری نیکسس اے آئی سے موسم کی معلومات، مٹی کی کوالٹی یا فصل کے بارے میں پوچھیں۔",
    jump_agronomy_title: "اسمارٹ ایگرونومی",
    jump_agronomy_desc: "زرعی زون کی بنیاد پر فصل کی ترتیب اور کھاد کا شیڈول بنائیں۔",
    jump_plant_title: "پودوں کی تشخیص",
    jump_plant_desc: "بیماریوں کی شناخت اور ان کے حل کے لیے اپنے پودوں کی تصویر اپ لوڈ کریں۔",
    
    // AI Advisory Input
    chat_placeholder: "فصلوں، بیماریوں یا مٹی کے بارے میں پوچھیں...",
    chat_welcome: "اسلام علیکم! میں آپ کا ایگری نیکسس اے آئی مشیر ہوں۔ میں مٹی کی رپورٹس کا تجزیہ، تصاویر سے پودوں کی بیماریوں کی تشخیص اور کھاد کے مناسب شیڈول کی سفارش کر سکتا ہوں۔ میں آج آپ کی کیا مدد کروں؟",
    chat_history_title: "ماضی کی سوالات",
    chat_history_loading: "ہسٹری لوڈ ہو رہی ہے...",
    chat_attach_tooltip: "فائل منسلک کریں",
    chat_history_tooltip: "سوالات کی ہسٹری دیکھیں",
    
    // Smart Agronomy View
    agro_zone_label: "زرعی زون منتخب کریں",
    agro_advisory_title: "اے آئی مٹی کی صحت کا جائزہ",
    agro_recommended_crops: "تجویز کردہ فصلیں",
    agro_crops_subtitle: "آپ کی مٹی کی ساخت اور موجودہ حالات کے مطابق بہترین فصلیں",
    agro_fit_confidence: "مٹی کی ساخت کا تناسب",
    agro_diagnostic_metrics: "حقیقی اشارے",
    agro_sand_silt: "ریت اور گاد کا تناسب:",
    agro_temp: "مٹی کا درجہ حرارت:",
    agro_moisture: "مٹی کی نمی (گھنٹہ وار):",
    agro_humidity: "موسمی نمی (ہوا):",
    agro_no_recs: "کوئی سفارشات پیدا نہیں کی گئیں۔",
    agro_soil_type: "مٹی کی قسم",
    agro_moisture_state: "نمی کی حالت",
    agro_ph_level: "پی ایچ کی سطح",
    agro_organic_carbon: "نامیاتی کاربن",
    agro_clay_content: "چکنی مٹی کا تناسب",
    agro_bulk_density: "کثافتِ مٹی",
    agro_match_likelihood: "مطابقت کا امکان",
    agro_accuracy: "درستگی",
    agro_training_size: "تربیتی ڈیٹا",
    agro_samples: "نمونے",
    agro_ready_title: "تجزیہ کے لیے تیار ہے",
    agro_ready_desc: "طبی خصوصیات کے جائزے اور کلاسیفیکیشن کے لیے بائیں جانب مٹی کی تصویر اپ لوڈ کریں۔",
    agro_loading_weather: "موسم کا حال لوڈ ہو رہا ہے...",
    agro_weather_unavailable: "موسم کا حال دستیاب نہیں برائے",
    auth_login: "لاگ ان",
    auth_register: "رجسٹر کریں",
    auth_email: "ای میل ایڈریس",
    auth_password: "پاس ورڈ",
    auth_select_role: "عہدہ منتخب کریں",
    auth_role_farmer: "کسان",
    auth_role_admin: "ایڈمن",
    auth_btn_access: "ڈیش بورڈ پر جائیں",
    auth_full_name: "پورا نام",
    auth_location: "شہر / مقام",
    auth_land_size: "زمین کا رقبہ (ایکڑ)",
    auth_btn_create: "اکاؤنٹ بنائیں",
    auth_select_land: "رقبہ منتخب کریں...",
    auth_land_less_1: "1 ایکڑ سے کم",
    auth_land_1_5: "1 - 5 ایکڑ",
    auth_land_5_10: "5 - 10 ایکڑ",
    auth_land_10_20: "10 - 20 ایکڑ",
    auth_land_20_50: "20 - 50 ایکڑ",
    auth_land_50_plus: "+50 ایکڑ",
    plant_card_title: "پودوں کی تصویر اور تشخیص",
    plant_drop_title: "پودے کی تصویر یہاں ڈراپ کریں",
    plant_drop_subtitle: "سائز 5MB تک، فارمیٹ JPG, JPEG, PNG",
    plant_btn_run: "تشخیص شروع کریں",
    plant_btn_reset: "فارم دوبارہ ترتیب دیں",
    plant_history_title: "پودوں کی پرانی تشخیصی رپورٹیں",
    plant_history_refresh: "ہسٹری تازہ کریں",
    plant_th_img: "پودے کی تصویر",
    plant_th_species: "شناخت شدہ قسم",
    plant_th_confidence: "اعتماد کی شرح",
    plant_th_condition: "صحت کی حالت",
    plant_th_issues: "پائے جانے والے مسائل",
    plant_th_date: "تجزیہ کی تاریخ",
    plant_th_action: "عمل",
    plant_history_empty: "کوئی تشخیصی ریکارڈ دستیاب نہیں ہے۔",
    agro_live_weather: "موسم کا حال",
    agro_district_stats: "اضلاعی پیداوار کے اعداد و شمار (2022-23)",
    agro_soil_photo_title: "مٹی کا تصویری تجزیہ",
    agro_soil_drop_title: "مٹی کی تصویر یہاں ڈراپ کریں",
    agro_soil_drop_subtitle: "یا فائلز براؤز کرنے کے لیے کلک کریں",
    agro_btn_analyze: "مٹی کی صحت کا تجزیہ کریں",
    plant_report_title: "صحت کی تشخیصی رپورٹ",
    plant_empty_title: "کوئی تجزیہ نہیں کیا گیا",
    plant_empty_desc: "پودوں کی اقسام اور صحت کا تجزیہ کرنے کے لیے بائیں جانب تصویر اپ لوڈ کریں۔",
    plant_lbl_species: "شناخت شدہ قسم",
    plant_lbl_health: "صحت کا اسکور",
    plant_lbl_issues: "پائے جانے والے مسائل / کمیاں",
    plant_lbl_insights: "اے آئی پیتھالوجی کے نتائج",
    plant_lbl_causes: "ممکنہ وجوہات:",
    plant_lbl_treatment: "علاج کے لیے عملی رہنمائی",
    plant_lbl_prevention: "احتیاطی تدابیر",
    plant_lbl_severity: "شدت کا درجہ"
  }
};
